title: 記録
description: vzvu3k6k
url: https://vzvu3k6k.tk
commit_permalink: https://github.com/vzvu3k6k/vzvu3k6k.tk/commit/{id}
permalink: /memo/:year/:month/:day/:title.html
feed: atom.xml
author:
  name: vzvu3k6k
  email: vzvu3k6k@gmail.com
  mailhide: https://mailhide.io/e/qfAtO
timezone: Asia/Tokyo

markdown: CommonMark

commonmark:
  options: [UNSAFE, SMART, FOOTNOTES]
  extensions: [autolink, table]

sass:
  style: expanded
  deploy_style: compressed
  compile_in_place: false

plugins:
  - jekyll-sitemap

exclude: [Gemfile, Gemfile.lock, build, ',']
