title: 記録
description: vzvu3k6k
baseurl: http://vzvu3k6k.tk/memo
feed: atom.xml
author:
  name: vzvu3k6k
  email: vzvu3k6k@gmail.com
  mailhide: http://www.google.com/recaptcha/mailhide/d?k=01Jtza220vCJ3GghRBqzxWuA==&c=FN3HMylmhSPQOyHxZNbCZl95-QlC2ep1WUsa2Azom9I=

markdown: rdiscount

exclude: [spec, Gemfile, Gemfile.lock, config.ru, build]