title: 記録
description: vzvu3k6k
baseurl: /memo/
url: http://vzvu3k6k.tk
commit_permalink: https://github.com/vzvu3k6k/vzvu3k6k.tk/commit/{id}
permalink: /memo/:year/:month/:day/:title.html
feed: atom.xml
author:
  name: vzvu3k6k
  email: vzvu3k6k@gmail.com
  mailhide: http://www.google.com/recaptcha/mailhide/d?k=01Jtza220vCJ3GghRBqzxWuA==&c=FN3HMylmhSPQOyHxZNbCZl95-QlC2ep1WUsa2Azom9I=

markdown: CommonMark

commonmark:
  options: [SMART, FOOTNOTES]
  extensions: [autolink, table]

sass:
  style: expanded
  deploy_style: compressed
  compile_in_place: false

plugins:
  - jekyll-sitemap

exclude: [Gemfile, Gemfile.lock, build]
