name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    # branches:
    #   - source

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.3
        env:
          JEKYLL_PAT: ${{ secrets.PERSONAL_TOKEN }}
